apiVersion: v1
kind: Secret
metadata:
  name: jfrog-cred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0YXhpMDQuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIllXaHRaV1JvWVcxeVlXbzZRWE50ZFVBeU1ESTEiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
